from pymessagebus._commandbus import CommandBus
from apps.booking.commandBus.commands import CreateBookingCommand, DeleteBookingCommand
from apps.booking.commandBus.command_handlers import handle_create_booking, handle_delete_booking

booking_command_bus = CommandBus(locking=True)
booking_command_bus.add_handler(CreateBookingCommand, handle_create_booking)
booking_command_bus.add_handler(DeleteBookingCommand, handle_delete_booking)
