from apps.core.dispatcher import EventDispatcher
from apps.payment.events.events import PaymentSuccessEvent, SubscriptionCancellationEvent
from apps.payment.events.event_handlers import send_payment_success_email, send_subscription_cancelled_email

payment_event_dispatcher = EventDispatcher()
payment_event_dispatcher.add_handler(PaymentSuccessEvent, send_payment_success_email)
payment_event_dispatcher.add_handler(SubscriptionCancellationEvent, send_subscription_cancelled_email)