# Generated by Django 5.2.7 on 2025-10-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'ordering': ['date']},
        ),
    ]
