# Generated by Django 5.2.7 on 2025-10-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_classes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='recurrence_days',
            field=models.JSONField(blank=True, help_text='List of weekdays for weekly recurrence, e.g., [0, 2] for Mon & Wed', null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='recurrence_type',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=10, null=True),
        ),
    ]
