# Generated by Django 5.2.7 on 2025-10-17 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classes_recurrence_days_classes_recurrence_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='parent_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_classes', to='classes.classes'),
        ),
    ]
