# Generated by Django 5.2.7 on 2025-10-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_classes_parent_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='recurrence_type',
            field=models.CharField(blank=True, choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=10, null=True),
        ),
    ]
