# Generated by Django 5.2.8 on 2025-12-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_classes_recurrence_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='description',
            field=models.TextField(),
        ),
    ]
