# Generated by Django 5.2.7 on 2025-10-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_passpurchase_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='passpurchase',
            name='is_cancel_requested',
            field=models.BooleanField(default=False),
        ),
    ]
