# Generated by Django 5.2.8 on 2025-11-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_passpurchase_is_cancel_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='passpurchase',
            name='stripe_idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
